date: last-modified

project:
  type: website
  output-dir: _site

site-url: https://wuqui.github.io/Lex252/

website:
  title: "Lex252"
  description: "Lexicology and Lexicography"
  navbar:
    left:
      - text: "Sessions"
        menu:
          - text: "01 — Introduction"
            href: sessions/01_intro/01_intro.qmd
          - text: "02 — The lexicon"
            href: sessions/02_lexicon/02_lexicon.qmd
          - text: "03 — Morphology"
            href: sessions/03_morphology/03_morphology.qmd
          - text: "04 — Dictionaries"
            href: sessions/04_dictionaries/04_dictionaries.qmd
          - text: "05 — Using dictionaries"
            href: sessions/05_dictionaries-2/05_dictionaries-2.qmd
          - text: "06 — Corpora"
            href: sessions/06_corpora/06_corpora.qmd
          - text: "07 — Semantics"
            href: sessions/07_semantics/07_semantics.qmd
  page-navigation: true
  search: true

format:
  html:
    theme: light
    toc: true
    css: document.css
    fig-cap-location: top
    fig-align: center
  clean-revealjs:
    slide-level: 2
    css:
      - slides.css
    fig-cap-location: top
    fig-align: center
    excalidraw:
      button: false
      shortcut: "`"
      theme: "light"

filters:
  - auto-dark
  - exclude
  - filters/fullcite.lua

revealjs-plugins:
  - pointer
  - excalidraw

bibliography: references.bib

metadata:
  linkprefix: ""

params:
  show_excl: false