name: Publish Quarto Site

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Render Quarto Project
        run: quarto render
      - name: Strip speaker notes from published slides
        run: |
          # Strip speaker notes from all RevealJS slides
          find _site -name "slides.html" -type f -exec sed -i '/<aside class="notes">/,/<\/aside>/d' {} +
      - name: Generate PDFs from slides
        run: ./scripts/generate-pdfs.sh
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site



